# 前端 Dockerfile
FROM node:20.12.2 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --force
COPY . .
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm run build -- --mode production

FROM nginx:1.25-alpine
COPY --from=builder --chown=nginx:nginx /app/dist /usr/share/nginx/html
COPY --chown=nginx:nginx nginx/nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]